lab-brussels-1/The-first-group

planning/user-personas.md
=> Adding new branch and a user-personas.md

planning/backlog.md
=> Added backlog.md

planning/communication-plan.md, planning/constraints.md, planning/retrospective.md
=> Updated material files

package-lock.json, planning/communication-plan.md
=> Minju communication plan PR

planning/README.md
=> Planning readme edition

planning/communication-plan.md
=> carsiti-comunication-plan

planning/communication-plan.md, planning/user-personas.md
=> zerubabel4 Update user-personas.md

planning/communication-plan.md
=> communicationupdate

planning/user-personas.md
=> Updated user personas

planning/backlog.md
=> Updated Backlog.md

planning/constraints.md
=> Carsiticonstrain2

planning/constraints.md
=> constrainfileupdate

planning/user-personas.md
=> Minju User-persona updated PR

planning/backlog.md
=> Finished planning/backlog.md

planning/user-personas.md
=> Update for planning/user-personas.md

planning/communication-plan.md
=> Update for planning/communication-plan.md

planning/communication-plan.md
=> Added some images of trees

planning/retrospective.md
=> Maria retrospective

index.html, styles/something.css
=> Minjufooter

index.html, planning/development-strategy.md, styles/something.css
=> Minjuupdate

index.html, planning/development-strategy.md, styles/something.css
Reverts lab-brussels-1/The-first-group#64
=> Revert "Minjuupdate"

styles/something.css
=> Added css for intro

planning/development-strategy.md
=> file updated

index.html
=> image added from assets folder
